# Generated by Django 2.1.2 on 2018-11-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longtitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('direction', models.IntegerField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('date', models.DateTimeField(verbose_name='date uploaded')),
            ],
        ),
    ]
