# Generated by Django 2.1.2 on 2018-11-29 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photomap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photoby',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='photo',
            name='direction',
            field=models.IntegerField(default=-1),
        ),
    ]
